scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairWest, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level2`)
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairLadder)
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ............e.e.................
    .........ee.eee.ee..............
    .........e3e111e3e..............
    ..........e1f1f1eeeeeeeee.......
    ..........e11111e11eee111eee....
    ..........2e33e321111111eee.e...
    ..........23333321ee111eeee.e...
    ...........222221ee111eeeee.e...
    ...........e11111e11e1111e..ee..
    ............e11111e23e111e..ee..
    .............e1e1e..22e1e1e.e...
    .............e1e1e....e1e1e.....
    .............e4e4e....e4e4e.....
    .............eeee.....eeee......
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
tiles.setTilemap(tilemap`level_1`)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairLadder)
scene.cameraFollowSprite(mySprite)
info.startCountdown(15)
