scene.onOverlapTile(SpriteKind.Player, sprites.castle.rock1, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level4`)
    tiles.placeOnRandomTile(mySprite, sprites.castle.shrub)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairWest, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level14`)
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairLadder)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile8`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level5`)
    tiles.placeOnRandomTile(mySprite, sprites.builtin.coral2)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.saplingOak, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level3`)
    tiles.placeOnRandomTile(mySprite, sprites.castle.rock2)
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ............e.e.................
    .........ee.eee.ee..............
    .........e2e111e2e..............
    ..........e1f1f1eeeeeeeee.......
    ..........e11111e11444111eee....
    ..........3e22e2311111144ee.e...
    ..........322222314411444ee.e...
    ...........33333144111444ee.e...
    ...........e11111411e1441e..ee..
    ............e41111e32e114e..ee..
    .............e1e1e..33e1e1e.e...
    .............e1e1e....e1e1e.....
    .............e4e4e....e4e4e.....
    .............eeee.....eeee......
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
tiles.setTilemap(tilemap`level_1`)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairLadder)
scene.cameraFollowSprite(mySprite)
info.startCountdown(60)
